### ISSUE TITLE
Performance problem: too many useless memory copy

### ISSUE THREAD

**Issue by daikiyamanaka** [daikiyamanaka/L0-gradient-smoothing#1]

**Comment by RoyiAvital** [comment]
How fast is this implementation compared to the reference?
How is it compared to [OpenCV `L0 Smooth` implementation](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/l0_smooth.cpp)?

**Comment by daikiyamanaka** [comment]
I think OpenCV implementation would be faster than my code, because it solves linear system in frequency domain.

In original paper, authors mentions that they solve equation (8)  for speedup, but my code solves equation (7) in image domain.

**Comment by RoyiAvital** [comment]
I see.
I don't see you utilize OpenMP / Threading as well.

How much time it takes to process ~16 MP image?

**Comment by daikiyamanaka** [comment]
Yes. I should parallelize the code.

I confirmed that it takes more than ten minutes to process 19 MP image with my laptop.
